services:
  sipros:
    build: .
    image: sipros
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    init: true
    working_dir: /workspace/sipros
    volumes:
      - .:/workspace/sipros
    environment:
      PYTHONUNBUFFERED: "1"
    stdin_open: true
    tty: true
